apiVersion: v1
kind: Pod
metadata:
  name: kubia-multi
spec:
  containers:
  - image: shoutakenaka/kubia
    env:
    - name: PORT
      value: "8080"
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
  - image: shoutakenaka/kubia
    env:
    - name: PORT
      value: "8090"
    name: kubia2
    ports:
    - containerPort: 8090
      protocol: TCP
